name: TDS GA0 Q13

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3001370@ds.study.iitm.ac.in
        run: echo "Hello, world!"
